// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://jqpxlqggkstytgrkyhyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxcHhscWdna3N0eXRncmt5aHliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4ODI2ODcsImV4cCI6MjA3NjQ1ODY4N30.TnjXdbtYQJ8w17FaHlbi1FHbTInxzQvFqg9HCa8saBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: false,
      autoRefreshToken: true,
    },
  }
);
